
DROP TABLE Club CASCADE; 
Drop TAble Run CASCADE;
DROP TABLE Trail CASCADE;
DROP TABLE Mountain CASCADE;
DROP TABLE Race CASCADE;
DROP TABLE Official CASCADE;
DROP TABLE Coach CASCADE;
DROP TABLE Racer CASCADE;
DROP TABLE Person CASCADE;
DROP TABLE Sponsor CASCADE;
